### PR TITLE
try to fix sphinx rendering

### LINKED ISSUE #55: api doc formatting of argument lists messed up
In https://becksteinlab.github.io/propkatraj/api.html , the argument name and type are not separated.

### PR DESCRIPTION
**Pull request by IAlibay**
Fixes #55

### CODE REVIEW

**Comment by IAlibay** [comment]
Let's see how it renders.

**Comment by IAlibay** [comment]
Thoughts on this @orbeckst ? https://propkatraj--56.org.readthedocs.build/en/56/api.html

**Review by orbeckst — APPROVED** [review]
Hah, go figure. Forgot our standard sphinx extensions. (and the intersphinx links – good that you noticed) Thanks for the fix, looks perfect.

**Comment by IAlibay** [comment]
Something is looking weird on the sidebar, I don't understand why it's separating the attributes that way...

**Comment by IAlibay** [comment]
Looking at the MDA docs this seems to be the way things are rendered now (might be a new upstream change). Let's go with it for now.

**Pull request merged**
