### PR TITLE
do not run codecov for cron CI

### LINKED ISSUE #59: remove CRON CI codecov
See https://github.com/MDAnalysis/cookiecutter-mdakit/issues/54 

Solution: don't run codecov on CRON CI

### PR DESCRIPTION
**Pull request by orbeckst**
fix #59

### CODE REVIEW

**Review by IAlibay — APPROVED** [review]

**Comment by orbeckst** [comment]
GH actions are not running. That's a bit suspicious. Did I break it with bad formatting??

I'll fiddle with it to see if I can get it to run.

**Comment by IAlibay** [comment]
@orbeckst I'm going to cycle this PR quickly.

**Comment by IAlibay** [comment]
There you go - the workflow was disabled because it's been > 60 days since the repo had a merge commit.

**Comment by IAlibay** [comment]
tests against main are failing because mda is now py3.9+

**Comment by orbeckst** [comment]
This is a question for maintenance of an mdakit (cc @fiona-naughton): "What should I do when suddenly the tests against the MDA develop branch fail?"

Should we make a new minor release of propkatraj that bumps version requirements?

**Comment by orbeckst** [comment]
In the meantime, I suppose I can remove 3.8 from the matrix for develop testing.

**Review by ianmkenney — APPROVED** [review]
LGTM

**Comment by orbeckst** [comment]
Do you want to merge it even though 3.8 fails?

**Comment by IAlibay** [comment]
yeah let's fix 3.8 in a separate PR

**Pull request merged**
