### PR TITLE
Sets up Travis/Codecov + basic regression tests

### PR DESCRIPTION
**Pull request by IAlibay**
Towards #20 

Changes made:
  - Adds the required Travis & Codecov files
  - Adds a few basic regression tests
    - Note: the assumption here is that the MDA PDB writer is accurate & that propka 3.1 will give intended results when given a file (i.e. the tests only really test that the PDBs are being correctly passed and the correct data structure is generated).

### CODE REVIEW

**Comment by IAlibay** [comment]
Ideally I'd also want to test that bad frames are being skipped as expected (https://github.com/Becksteinlab/propkatraj/issues/10#issuecomment-342518668). However, I'm not sure if the files are GPL compliant.

**Review by orbeckst — APPROVED** [review]
Thank you for all this work, @IAlibay !

Looks all fine to me. What I didn’t understand was the question regarding licensing of data files. Can you explain what your concern is?

**Comment by IAlibay** [comment]
> Thank you for all this work, @IAlibay !
> 
> Looks all fine to me. What I didn’t understand was the question regarding licensing of data files. Can you explain what your concern is?

Sorry, what I meant was; is it ok to include the files that @rsexton2 added in #10 and #13 under the GPLv3 licence of propkatraj? (my understanding is that @rsexton2 is a member of your lab @orbeckst ?)

(I think we usually check this in MDA before adding user contributed files, so I didn't want to make any assumptions here).

**Comment by orbeckst** [comment]
All three sets of datafiles are fine to be included under GPLv3.

Thanks for being very thorough.

**Pull request merged**
