### PR TITLE
Set up proper documentation with Sphinx

### PR DESCRIPTION
**Pull request by ianmkenney**

### CODE REVIEW

**Comment by ianmkenney** [comment]
@IAlibay @orbeckst looks ready for a review. I will change the target branch for the documentation to master once we merge into `dev`. Find the documentation at https://becksteinlab.github.io/propkatraj

**Comment by IAlibay** [comment]
Could you get RTD to build on PRs? it'd probably make reviewing going forward a lot simpler?

**Comment by ianmkenney** [comment]
You mean build on RTD in addition to GitHub?

**Comment by IAlibay** [comment]
you can make it so that you only build on RTD for pull requests, that way you have somewhere that's auto generated on PR and you only update the docs properly once you've merged. The userguide is a good example of that.

**Comment by ianmkenney** [comment]
@IAlibay RTD is building the PR, but I don't want RTD outside of the PR, do you know how to disable it?

**Comment by ianmkenney** [comment]
@orbeckst this looking good to squash and merge?

**Review by orbeckst — APPROVED** [review]
Looks good. 

Two minor comments
- are the Gh pages pushed for the PR?? If yes, that’s not right, it should only be pushed when merged into main
- Good that RTD is built, I was just a bit confused that the link under the check lead to the page https://readthedocs.org/projects/propkatraj/builds/19412363/ and not directly to the built docs

**Pull request merged**
